[package]
name = "auto-release"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
zip = "0.6"
walkdir = "2.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
